# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-14 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shiptrader', '0003_listing_activite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='activite',
            new_name='active',
        ),
    ]
